AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GitHubRepoName: 
    Type: String
    Description: Name of the GitHub repository
    Default: "aws_pipeline"
  GitHubBranch: 
    Type: String
    Description: Branch of the GitHub repository to monitor
    Default: "main"

Resources:
  PipelineArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-artifact-store-bucket-name

  PipelineSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-source-bucket-name
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-artifact-bucket-name

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyCICDPipeline
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactStore
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '2'
              Configuration:
                Owner: karamullah69
                Repo: !Ref GitHubRepoName
                Branch: !Ref GitHubBranch
                OAuthToken: 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

              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
        - Name: Dev
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: AwsPipeline
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: Proceed with deployment to QA
              RunOrder: 2
        - Name: QA
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: Proceed with deployment to UAT
              RunOrder: 1
        - Name: UAT
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: Proceed with deployment to Prod
              RunOrder: 1
        - Name: Prod
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: Deployment complete
              RunOrder: 1

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: PipelineRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${PipelineSourceBucket}/*'
                  - !Sub 'arn:aws:s3:::${PipelineArtifactBucket}/*'
              - Effect: Allow
                Action:
                  - codepipeline:*
                Resource: "*"
    DependsOn: PipelineArtifactStore
