AWSTemplateFormatVersion: 2010-09-09
Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: bucketkola
        Type: S3
      RoleArn: arn:aws:iam::674100930412:role/PipelineRole
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              Configuration:
                RepositoryName: my-repo
                BranchName: main
              OutputArtifacts:
                - Name: MyAppSource
              RunOrder: 1
        - Name: Dev
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: my-build-project
              InputArtifacts:
                - Name: MyAppSource
              OutputArtifacts:
                - Name: BuildOutputDev
              RunOrder: 1
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration: {}
              RunOrder: 2
        - Name: QA
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: my-build-project
              InputArtifacts:
                - Name: MyAppSource
              OutputArtifacts:
                - Name: BuildOutputQA
              RunOrder: 1
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration: {}
              RunOrder: 2
        - Name: UAT
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: my-build-project
              InputArtifacts:
                - Name: MyAppSource
              OutputArtifacts:
                - Name: BuildOutputUAT
              RunOrder: 1
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration: {}
              RunOrder: 2
        - Name: Prod
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: my-build-project
              InputArtifacts:
                - Name: MyAppSource
              OutputArtifacts:
                - Name: BuildOutputProd
              RunOrder: 1
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration: {}
              RunOrder: 2
